name: Build and Push Docker Image

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repo
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Verify directory structure from root
        run: |
          echo "--- Verifying Directory Structure from Repository Root ---"
          echo "Current directory: $(pwd)"
          echo "Listing all files and directories at root:"
          ls -la
          if [ ! -d "./backend" ]; then
            echo "Error: Backend directory './backend' not found at repository root."
            exit 1
          else
            echo "Backend directory './backend' found."
            echo "Listing contents of './backend':"
            ls -la ./backend # Check if 'dockerfile' is visible here
          fi
          echo "--- End of Directory Structure Verification ---"

      # Step 2: Log in to DockerHub
      - name: Log in to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Step 3: Build Docker image
      - name: Build the Docker image
        working-directory: ./backend
        run: | 
          echo "--- Inside Build Step (current working-directory should be ./backend) ---"
          echo "Current directory: $(pwd)"
          echo "Listing files in current directory (should be contents of backend/):"
          ls -la # Verify 'dockerfile' (lowercase) is here and other backend files

          echo "Attempting to build Docker image..."

          docker build \ 
            -t sankhasuvra/expense-tracker:v1 \
            -t sankhasuvra/expense-tracker:${{ github.sha }} \
            .

          echo "docker build command finished"
          echo "--- End of Build Step ---"
      # Step 4: Push Docker image to DockerHub
      - name: Push the Docker image
        run: |
          docker push sankhasuvra/expense-tracker:v1
          docker push sankhasuvra/expense-tracker:${{ github.sha }}
